# 這裡會為本專案產生一組安全很長的密碼
apiVersion: v1
kind: Secret
metadata:
  name: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-secret
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: MYSQL_ROOT_PASSWORD
stringData:
  username: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}
